### PR TITLE
Added Views

### PR DESCRIPTION
**Pull request by stanleySimeon**
# In this milestone I created:

  - [x] views for users that showing
    _user posts_
    _user comments_
    _user likes_

  - [x] views for posts that showing
    _post ID_
    _number of likes_
    _number of comments_

### CODE REVIEW

**Review by AshakaE — APPROVED** [review]
Hi @stanleySimeon  , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Pull request 👍 
- Git flow ✅ 
## Required Changes ♻️

- [x] Kindly push the files with code changes, so it can be reviewed 🙏 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by stanleySimeon** [comment]
Hello @AshakaE, I'm not sure that I understand what are you saying to
Kindly, can you give me more explanations, please!?

**Comment by AshakaE** [comment]
> Hello @AshakaE, I'm not sure that I understand what are you saying to Kindly, can you give me more explanations, please!?

If you go to the tab `Files changed` in this PR, there's no file to review there

**Comment by stanleySimeon** [comment]
@AshakaE, thanks for your help!
Kindly, it's always better to specify what could be changed!

**Review by uwadonat — APPROVED** [review]
## Hi @stanleySimeon,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
### Highlights
- No linter errors ✔️
- Descriptive pull request message ✔️
appr2

# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Pull request merged**
