### PR TITLE
Features Branch

### PR DESCRIPTION
**Pull request by stanleySimeon**
# In this milestone I added:

  - users table
  - comments table
  - likes table
  - posts table

- [ ] using migration to migrate the database schema

### CODE REVIEW

**Review by AshakaE — CHANGES_REQUESTED** [review]
Hi @stanleySimeon 🙋 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
Pull request is 👌 
No linter errors ✔️ 


## Required Changes ♻️

- [x] Kindly add the migration files for `likes` and `posts`

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by stanleySimeon** [comment]
hello @AshakaE, How are you doing?

**Comment by stanleySimeon** [comment]
I added the migration for all of the files
Kindly, can you be precise for me, please?

**Comment by AshakaE** [comment]
> hello @AshakaE, How are you doing?
> 

Hi @stanleySimeon 👋

**Comment by AshakaE** [comment]
> > hello @AshakaE, How are you doing?
> > 
> 
> Hi @stanleySimeon 👋 

2 files are missing from your PR specifically `likes` and `posts` , I also checked the code branch but they aren't there

**Comment by AshakaE** [comment]
> > hello @AshakaE, How are you doing?
> > 
> 
> Hi @stanleySimeon 👋 

2 files are missing from your PR specifically `likes` and `posts` , I also checked the code branch but they aren't there

**Comment by stanleySimeon** [comment]
@AshakaE, I'm so sorry, I didn’t add those files before pushing!
Thanks a lot!😁

**Comment by stanleySimeon** [comment]
@AshakaE, kindly you can check it now!

**Review by MeqdamAlqudah — APPROVED** [review]
Hi @stanleySimeon , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AshakaE** [comment]
> @AshakaE, I'm so sorry, I didn’t add those files before pushing!
> Thanks a lot!😁
> 
> 

No problem 👍

**Pull request merged**
